url: "http://git.eitanblumin.com/CRUDE-ASP"
future: true
baseurl: "/CRUDE-ASP"
logo: /crude-logo.png
social-network-links:
  rss: false
  email: "eitan@madeiradata.com"
  google-plus: +EitanBlumin
  linkedin: eitanblumin
  github: EitanBlumin
  twitter: EitanBlumin
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
navbar-links:
  About Me: "aboutme"
  Resources:
    - GitHub Gists: "https://gist.github.com/EitanBlumin"
    - LinedIn: "https://www.linkedin.com/in/eitanblumin/"
  Author's home: "https://www.eitanblumin.com/"
theme: jekyll-theme-leap-day
