CREATE VIEW [portal].[DataViewFieldTypes]
AS
SELECT *
FROM (VALUES
 (1, 'Text', '''', 'text')
,(2, 'Text Area', '''', 'textarea')
,(3, 'Integer', '', 'numeric')
,(4, 'Decimal', '', 'numeric')
,(5, 'Dropdown Box', '', 'select')
,(6, 'Multi-Selection Dropdown Box', '''', 'csv')
,(7, 'Date', '''', 'date')
,(8, 'Date and Time', '''', 'datetime')
,(9, 'Boolean Switch', '', 'boolean_switch')
,(10, 'Link', '''', 'link')
,(11, 'Image Source', '''', 'image')
,(12, 'Password', '''', 'password')
,(13, 'Time', '''', 'time')
,(14, 'Rich Text', '''', 'rte')
,(15, 'E-Mail', '''', 'email')
,(16, 'Phone', '''', 'phone')
,(17, 'Multi-Selection Checkboxes', '''', 'csv_checkboxes')
,(18, 'Multi-Selection Switches', '''', 'csv_switches')
,(19, 'Multi-Selection Buttons', '''', 'csv_buttons')
,(20, 'Selection Radios', '', 'select_radios')
,(21, 'Selection Switches', '', 'select_switches')
,(22, 'Boolean Checkbox', '', 'boolean_checkbox')
,(23, 'Boolean Radios', '', 'boolean_radios')
,(24, 'Computed Expression', '''', 'formula')
,(25, 'Document Download', '''', 'document')
) AS V(TypeValue, TypeLabel, TypeWrappers, TypeIdentifier)
